import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import MovieSearch from './components/MovieSearch';
import useSWR, { Fetcher } from 'swr';

const fetcher: Fetcher<string, string> = (...args) =>
  fetch(...args).then((res) => res.json());

export type Movie = {
  id: number;
  name: string;
  movieRating: number;
};

export type Movies = {
  movies: Movie[];
};

const inter = Inter({ subsets: ['latin'] });

export default function Home({ ...props }) {
  const url = `https://api.themoviedb.org/3/movie/popular?language=en-US&page=1?api_key=${process.env.NEXT_PUBLIC_TMDB_API_KEY}`;
  const { data: result, error } = useSWR(url, fetcher);
  console.log(result)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
      </header>
      <main className={`${inter.className}`}>
        <div className={styles.description}>
          <MovieSearch />
        </div>
      </main>
    </>
  );
}
